-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- Adds PENDING: an engineer a case is assigned to (via Router.Escalate,
-- SetPresence's queue-drain, or Decline's reassignment) is now marked
-- PENDING, not BUSY, until they explicitly accept it (see the new
-- Router.Accept). BUSY is now reserved for an accepted, in-progress
-- session -- the CSM portal's status bar should only ever show yellow
-- Busy once the engineer has clicked Accept, per this feature's own
-- design. PENDING and BUSY both count as "has current_case_id set" for
-- every existing check in this schema and in internal/router (mid-session
-- presence handling, sticky routing, Decline's own-case check, etc.), so
-- nothing else here needs to change.
ALTER TYPE chat_routing.engineer_status ADD VALUE 'PENDING';
