-- Copyright (c) 2026 WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- Renames chat_conversation.engineer_id to assignee_id, matching the
-- "assignee" naming a normal work item uses -- a chat_conversation can be
-- genuinely unassigned (still AI-handled), same as a work item pre-triage.
-- Pure rename: this column was never foreign-keyed to cs_engineer_status.
ALTER TABLE chat_routing.chat_conversation RENAME COLUMN engineer_id TO assignee_id;
